# Generated by Django 5.2.7 on 2025-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdJourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
