# Generated by Django 5.2.7 on 2025-11-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdJourney', '0002_aboutme_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='documentation/')),
            ],
        ),
    ]
